#!/bin/bash

set -x

export IP=$(ifconfig | awk '/inet/ { print $2 }' | egrep -v '^fe|^127|^192|^172|::' | head -1)
export IP=${IP#addr:}

if [[ $HOSTNAME == "node"* ]] ; then
    #rightscale
    export IP=$(grep $(hostname) /etc/hosts | grep -v ext | awk '{print $1}')
fi

if [[ "$OSTYPE" == "darwin"* ]]; then
    # Mac OSX
    export IP=localhost
fi

ps -ef | grep graphql-dse | grep java | grep -v grep|awk '{print $2}' | xargs kill -9

mvn package

echo $IP

mvn exec:java -Dexec.mainClass="com.syllogistic.eightfour.GraphQLDseApplication" -Dexec.args="server conf/graphql-dse.yaml"
